2020-07-14 10:19:02,985 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:19:09,705 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:46:08,739 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:46:40,646 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:46:53,952 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:54:14,924 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:54:52,073 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 10:55:51,332 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 13:43:05,944 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 13:43:14,446 ERROR: Exception on / [GET] [in /home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/austin/Desktop/LearnFlask/microblog/app/routes.py", line 19, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-07-14 13:43:17,827 ERROR: Exception on /index [GET] [in /home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/austin/Desktop/LearnFlask/microblog/app/routes.py", line 19, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-07-14 13:43:22,610 ERROR: Exception on /index [GET] [in /home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/austin/Desktop/LearnFlask/microblog/app/routes.py", line 19, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-07-14 13:43:44,382 ERROR: Exception on /index [GET] [in /home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/austin/Desktop/LearnFlask/microblog/app/routes.py", line 19, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-07-14 13:43:49,920 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 13:44:46,737 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 13:45:00,419 ERROR: Exception on /index [POST] [in /home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austin/Desktop/LearnFlask/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/austin/Desktop/LearnFlask/microblog/app/routes.py", line 21, in index
    post = Post(body=form.post.data, author=current_user)
NameError: name 'Post' is not defined
2020-07-14 13:45:21,652 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
2020-07-14 13:47:25,039 INFO: Microblog startup [in /home/austin/Desktop/LearnFlask/microblog/app/__init__.py:30]
